[functions.proxy-html]
verify_jwt = true
max_retries = 3
timeout_ms = 5000

[functions.proxy-html.import_map]
imports = {
  "https://deno.land/std@0.168.0/http/server.ts" = "https://deno.land/std@0.168.0/http/server.ts",
  "https://deno.land/std@0.168.0/testing/asserts.ts" = "https://deno.land/std@0.168.0/testing/asserts.ts"
} 